spring:
    profiles:
        active: dev
        
        
---
spring: 
    profiles: test
    application:
        name: springcloud-config-test
        
---
spring: 
    profiles: dev
    application:
        name: springcloud-config-dev
    