spring:
  application:
    name: springcloud-config-test
  profiles: test
   
    
    
spring: 
  profiles:
    active: dev
    
 
spring:
  application:
    name: springcloud-config-dev
  profiles: dev
  
  
 
